export const fields = [
  {
    placeholder: 'Почта',
    validate: true,
    name: 'email',
    type: 'email',
    error: 'Почта должна содержать @',
    formName: 'email',
  },
  {
    placeholder: 'Логин',
    validate: true,
    name: 'login',
    type: 'text',
    error: 'Только англ. буквы, символ _ и точка',
    formName: 'login',
  },
  {
    placeholder: 'Имя',
    validate: true,
    name: 'first_name',
    type: 'text',
    error: 'Имя должно начинаться с заглавной буквы',
    formName: 'first_name',
  },
  {
    placeholder: 'Фамилия',
    validate: true,
    name: 'second_name',
    type: 'text',
    error: 'Фамилия должна начинаться с заглавной буквы',
    formName: 'second_name',
  },
  {
    placeholder: 'Телефон',
    validate: true,
    name: 'phone',
    type: 'phone',
    error: 'Телефон может начинаться с +7',
    formName: 'phone',
  },
  { 
    placeholder: 'Пароль',
    type: 'password',
    name: 'password',
    error: 'Мин. 8 - Макс. 40 символов, обязательно заглавная буква и цифра',
    validate: true,
    formName: 'password',
  },
  { 
    placeholder: 'Пароль (еще раз)',
    type: 'password',
    name: 'password',
    error: 'Мин. 8 - Макс. 40 символов, обязательно заглавная буква и цифра',
    validate: true,
    formName: 'repeatPassword',
  },
];
